### ISSUE TITLE
TimSort Implementation in C

### ISSUE THREAD

**Issue by aakritiguptaa** [TechyGuyAditya/Hacktoberfest-2022#40]
How is this feature related to the project?
An excellent advanced sorting algorithm where the average case and the worst case are of the same complexity

Describe the solution you'd like
A clear and concise solution can be found over the net

Would be amazing if I could be allowed to work on this.
My first time participating in Hacktober Fest

Thanks!
Aakriti

**Comment by TechyGuyAditya** [comment]
Yes, you can add any number of PRs you want here, and I will accept them for you.
