### ISSUE TITLE
README.md for the Repository

### ISSUE THREAD

**Issue by aakritiguptaa** [TechyGuyAditya/Hacktoberfest-2022#41]
Hello Maintainers!

I've noticed that the repository lacks a README.md, would be amazing if I could be assigned to this feature development

**How is the feature request related to a problem?**
The project lacks a clear and concise README.md file for newbies to look at and get guidance from.

**Describe the solution you'd like**
Including an introduction, guideline section, maintainers and contributor's section

**Additional context**
Would also include Hacktober 2022 images and hyperlinks

Thanks!
Aakriti

**Comment by TechyGuyAditya** [comment]
Yes, you can add it here if you want. Just, do not simply add "contributors" and leave it like that, it may seem to get spam-filtered. And, hacktoberfest is going to end in a few days anyways. I suggest you simply upload your own implemented code that you uploaded on leetcode in this repo. You can close this thread if you change your mind.
